"""
    Swagger Dummy Posts

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.post import Post
globals()['Post'] = Post
from openapi_client.model.posts import Posts


class TestPosts(unittest.TestCase):
    """Posts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPosts(self):
        """Test Posts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Posts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
